services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=zalupa'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - spring-postgres
    expose:
      - 5432

  backend:
    build:
      context: again
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=example
    networks:
      - spring-postgres

networks:
  spring-postgres:
